apiVersion: v1
kind: ServiceAccount
metadata:
  name: arkiv-ingestion-sa
  namespace: arkiv-ingestion
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arkiv-ingestion-db-sa
  namespace: arkiv-ingestion
automountServiceAccountToken: false
---