apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: dev-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - grafana-admin.enc.yaml
  - blockscout-postgres.enc.yaml
  - blockscout-app.enc.yaml
  - arkiv-ingestion-db.enc.yaml
